---
Title: How to restrict rds access with iam
layout: docs
---


== Overview


AWS IAM RDS authentication addresses the challenges due to password reusability and guessability by replacing passwords with a short lived (15 minute) token that is used when connecting to a database, generated using the AWS CLI. IAM database authentication is more secure than the native authentication methods because of the following reasons: +

* AM uses your AWS access keys to generate database authentication tokens. You don't need to store database user credentials.
* IAM database authentication requires an SSL connection. This encrypts all data that you transmit to and from your Amazon RDS DB instance.

== Worklfow:


== Procedure:
Restricting access to RDS instance to limited users and log in using only temporary access token into the instance. User is only allowed to connect to DB instance & not to perform any other action. 

**Steps to follow:** 

* Create a RDS instance and enable the password and IAM Authentication on the RDS DB instance.
(Database authentication > Password and IAM database authentication) +
* Create a database user to use IAM authentication with the database +
** Create a new user and grant it `rds_iam` role so that it should only login via RDS auth token. To create this user, use master credentials to login into the database and then create a new user. +
For PostgreSQL: +
`psql -h {database or cluster endpoint} -U {Master username} -d {dbname} -p {port}` +
[source]
CREATE USER <db_username>;
GRANT rds_iam TO <db_username>; 

* Create an IAM user and attach an IAM policy that maps the database user to the IAM user.
** Create an IAM user and attach the policy generated. This will grant permission to user to connect to database via auth token.
[source]
{
    "Statement": [
        {
            "Action": [
                "rds-db:connect"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:rds-db:<region>:<account-id>:dbuser:<DbiResourceId>/<db-username>"
            ],
            "Sid": "AllowFullAccess"
        }
    ],
    "Version": "2012-10-17"
}

* Generate an IAM Database Authentication Token +    
This token is a JSON Web Token (JWT) that contains the authentication information for the IAM user. To create an IAM database authentication token, follow these steps:

** Install AWS CLI
** Configure Profile: +
Configure the user in the CLI,having permission to connect to RDS instance.
[source]
export PROFILE_NAME="console_rds_user"
aws configure --profile $PROFILE_NAME
awsume $PROFILE_NAME
** Configure Variables:
[source]
export REGION="<YOUR-REGION>"
export RDSHOST="<RDS-ENDPOINT>"
export PG_USER="<DB-USERNAME>"
export PORT=<PORT>
export DB_NAME="<DB-NAME>"

** Generate Token:
[source]
export PGPASSWORD="$(aws rds generate-db-auth-token --hostname $RDSHOST --port $PORT --region $REGION --username $PG_USER)"

* Connect to the RDS PostgreSQL Instance using token
[source]
psql "host=$RDSHOST port=$PORT dbname=$DB_NAME user=$PG_USER password=$PGPASSWORD sslmode=require"

**Note:**

* IAM authentication doesn't support service-specific context keys that can be used in the condition element of policy statements. IAM authentication also doesn't support all global condition context keys.
* IAM policies are defined for the RDS level access like connection to rds, restricting user from deleting the DB instance, stopping instance, modifying RDS instance etc.
* To restrict user from any database related activity like restriction on deletion of schema or tables etc., then we need to assign that permissions to user on database level because IAM policies cannot control these database related permissions.






