---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deployment
  namespace: flux-trial
spec:
  interval: 30s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: deployment
