---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: deployment
  namespace: flux-trial
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/amannagpal2/deployment
