on:
  workflow_dispatch:

    

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: cfwweusbdevregistry.azurecr.io/ubuntu-devops:1.0.4
      credentials:
        username: ${{ secrets.MRT_CLIENT_ID }}
        password: ${{ secrets.MRT_CLIENT_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

